/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppkp2022jateng;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.util.logging.ConsoleHandler;
import java.util.logging.Logger;
import java.util.logging.Level;
import org.telegram.telegrambots.TelegramApiException;
import org.telegram.telegrambots.TelegramBotsApi;
import org.telegram.telegrambots.logging.BotLogger;
import org.telegram.telegrambots.logging.BotsFileHandler;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Devan
 */
public class frmTelegram extends javax.swing.JFrame {

    /**
     * Creates new form frmTelegram
     */
    Connection Con = frmTelegram.getConnection();
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    

    
    public frmTelegram() {
        initComponents();
        cekInternet();
        setResizable(false);
        getConnection();
        //Image frameIcon = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/resouce/laravel.png"));
        //this.setIconImage(frameIcon);
    }
    
    public static Connection getConnection(){
        Connection Con= null;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost/db_telebot", "root", "");
            System.out.println("");
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        return Con;
    }
    
//    public static void enData(){
//        try {
//            ps = Con.prepareStatement("INSERT INTO mhs(nim, nama, nilai_uts, nilai_uas, nilai_tugas, nilai_akhir, nilai_huruf, predikat) VALUES (?,?,?,?,?,?,?,?)");
//            ps.setString(1, NIM.getText()); ps.setString(2, nama.getText());
//            ps.setString(3, nUTS.getText()); ps.setString(4, nUAS.getText());
//            ps.setString(5, nTugas.getText());
//            ps.setString(6, nUTS2.getText()); ps.setString(7, nUAS2.getText());
//            ps.setString(8, nTugas2.getText());
//            ps.executeUpdate();
//            JOptionPane.showMessageDialog(null, "Data tersimpan");
//        } catch (SQLException e) {
//            System.out.println("Error: " + e.getMessage());
//        }
//    }

    public static void getMsg(String id, String msg, String name){
        String pesan = null;
        MyProjectHandler Send = new MyProjectHandler();
        if (msg.contains("/start")) {
            pesan = "Hallo " + name + " Apakabar?, Selamat mencoba bot ini ya :)";
            pesan += "\nUntuk menampilkan command yang tersedia silahkan gunakan /info";
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else if(msg.contains("/info")){
            pesan += "Hallo " + name + ", ini adalah command yang mungkin bisa kamu gunakan :)";
            pesan += "\n/info // untuk menampilkan seluruh command yang tersedia";
            pesan += "\n/developer // untuk menampilkan nama pembuat aplikasi ini";
            pesan += "\n/sapa // untuk menyapa user";
            pesan += "\n/3";
            pesan += "\n/4";
            pesan += "\n/5";            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else if(msg.contains("/developer")){
            pesan = "Aliv Okta Aseda";
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else if(msg.contains("/sapa")){
            pesan = "Selamat pagi " + name + ", Semoga hari anda menyenangkan :)";
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else if(msg.contains("/3")){
            pesan = "Selamat pagi";
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else if(msg.contains("/4")){
            pesan = "Selamat pagi";
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else if(msg.contains("/5")){
            pesan = "Selamat pagi";
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }else{
            Send.sendPesan(id, pesan);
            lstPesan.add("Send to : " + id +", Pesan : " + pesan);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstPesan = new java.awt.List();
        txtIdTelegram = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesan = new javax.swing.JTextArea();
        lblStatus2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblStatus3 = new javax.swing.JLabel();
        lblStatus4 = new javax.swing.JLabel();
        txtIdTelegram1 = new javax.swing.JTextField();
        lblStatus5 = new javax.swing.JLabel();
        txtIdTelegram2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblStatus6 = new javax.swing.JLabel();
        lblStatus7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdTelegram.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSend.setText("Broadcast");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus.setText("Status : ");

        lblStatus1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus1.setText("Message in & out");

        txtPesan.setColumns(20);
        txtPesan.setRows(5);
        jScrollPane1.setViewportView(txtPesan);

        lblStatus2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus2.setText("Broadcast Message");

        jButton1.setText("Clean");

        lblStatus3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus3.setText("Chat Id");

        lblStatus4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus4.setText("No Handphone");

        txtIdTelegram1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lblStatus5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus5.setText("Username");

        txtIdTelegram2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jButton2.setText("Hapus");

        jButton3.setText("Edit");

        jButton4.setText("Daftar");

        jButton5.setText("Refresh");

        lblStatus6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblStatus6.setText("*Pengisian CHAT ID setelah member terdaftar");

        lblStatus7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblStatus7.setText("Kelola Member");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Hp", "Username", "Chat Id"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus1)
                            .addComponent(lblStatus2)
                            .addComponent(lstPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatus6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStatus5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtIdTelegram2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus3)
                                    .addComponent(lblStatus4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtIdTelegram, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdTelegram1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblStatus7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblStatus7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdTelegram2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblStatus4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdTelegram1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdTelegram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton5)
                        .addComponent(lblStatus6)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblStatus2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        MyProjectHandler Send = new MyProjectHandler();
        Send.sendPesan(txtIdTelegram.getText(), txtPesan.getText());
        lstPesan.add("Send to : " + txtIdTelegram.getText() +", Pesan : " + txtPesan.getText());
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTelegram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTelegram().setVisible(true);
                BotLogger.setLevel(Level.ALL);
                BotLogger.registerLogger(new ConsoleHandler());
                try {
                    BotLogger.registerLogger(new BotsFileHandler());
                    } catch (IOException ex) {
                        Logger.getLogger(frmTelegram.class.getName()).log(Level.SEVERE, null,ex);
                }
                try {
                    TelegramBotsApi telegramBotsApi = createTelegramBotsApi();
                    try {
                        telegramBotsApi.registerBot(new MyProjectHandler(){
                        
                        });
                    } catch (TelegramApiException e){
                        
                    }
                } catch (Exception e){
                    
                }
            }
        });
    }
    
    private static TelegramBotsApi createTelegramBotsApi() throws TelegramApiException {
        TelegramBotsApi telegramBotsApi;
        telegramBotsApi = createlongPollingTelegramBotsApi();
        return telegramBotsApi;
        
    }
    
    private static TelegramBotsApi createlongPollingTelegramBotsApi() {
        return new TelegramBotsApi();
    }
    
    public void cekInternet() {
        try {
            URL url = new URL("http://google.co.id");
            URLConnection conn = url.openConnection();
            conn.connect();
            //konek = true;
            lblStatus.setText("Status : Internet Akses");
        } catch (Exception e) {
            //konek = false;
            lblStatus.setText("Status : Tidak Ada Internet");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus3;
    private javax.swing.JLabel lblStatus4;
    private javax.swing.JLabel lblStatus5;
    private javax.swing.JLabel lblStatus6;
    private javax.swing.JLabel lblStatus7;
    public static java.awt.List lstPesan;
    private javax.swing.JTextField txtIdTelegram;
    private javax.swing.JTextField txtIdTelegram1;
    private javax.swing.JTextField txtIdTelegram2;
    private javax.swing.JTextArea txtPesan;
    // End of variables declaration//GEN-END:variables
}